# Example:
# [as-set_as64496_example]
# AS_SET=AS64496:AS-EXAMPLE
# DESCR=Example AS-SET for Documentation
# MEMBERS=AS64496
# MEMBERS=AS64497
# NOTE: Unspecified fields are complemented from common.conf

[as-set_as64496_example]
AS_SET=
DESCR=
MEMBERS=
