# Example:
# [aut-num_as64496]
# AUT_NUM=AS64496
# AS_NAME=AS-EXAMPLE
# DESCR=Example Network for Documentation
# IMPORT=from AS65000 accept ANY
# EXPORT=to AS65000 announce AS64496
# MP_IMPORT=afi ipv6.unicast from AS65000 accept ANY
# MP_EXPORT=afi ipv6.unicast to AS65000 announce AS64496:AS-EXAMPLE
# NOTE: Unspecified fields are complemented from common.conf

[aut-num_as64496]
AUT_NUM=
AS_NAME=
DESCR=
IMPORT=
EXPORT=
MP_IMPORT=
MP_EXPORT=
