# Example:
# [mntner_example]
# mntner:     MAINT-AS64496
# descr:      Example Maintainer for Documentation
# auth:       MAIL-FROM noreply@example.com
#             or CRYPT-PW <password> (auto inserted if configured)
# mnt-nfy:    noc@example.com
# upd-to:     noc@example.com
# notify:     noc@example.com
# NOTE: Unspecified fields are complemented from common.conf

[mntner_example]
mntner:     
descr:      
AUTH=
mnt-nfy:    
upd-to:     
