# Example:
# [mntner_example]
# MNTNER=MAINT-AS64496
# DESCR=Example Maintainer for Documentation
# AUTH=MAIL-FROM noreply@example.com
# or CRYPT-PW will be inserted automatically when configured
# MNT_NFY=noc@example.com
# UPD_TO=noc@example.com
# NOTE: Unspecified fields are complemented from common.conf

[mntner_example]
MNTNER=
DESCR=
AUTH=
MNT_NFY=
UPD_TO=
