# Example:
# [route-v6_2001-db8-_32]
# prefix=2001:db8::/32
# origin=AS64496
# descr=Example Route6 Object for Documentation
# NOTE: Unspecified fields are complemented from common.conf

[route-v6_2001-db8-_32]
prefix=
origin=
descr=
