# Example:
# [route-v4_192.0.2.0_24]
# prefix=192.0.2.0/24
# origin=AS64496
# descr=Example Route Object for Documentation
# NOTE: Unspecified fields are complemented from common.conf

[route-v4_192.0.2.0_24]
prefix=
origin=
descr=
