# Example:
# [route-v4_192.0.2.0_24]
# PREFIX=192.0.2.0/24
# ORIGIN=AS64496
# DESCR=Example Route Object for Documentation
# NOTE: Unspecified fields are complemented from common.conf

[route-v4_192.0.2.0_24]
PREFIX=
ORIGIN=
DESCR=
