##
## Registry profile: JPIRR
##

## common settings
whois_address="jpirr.nic.ad.jp"
irr_mail_address="auto-dbm@nic.ad.jp"
SOURCE="JPIRR"
UPDATE_METHOD="email"
AUTH_METHOD="pw_in_body"

## Continuation Options
## Keys listed here must be defined in "Organization Parameters"
CONTINUATION_TARGET_DESCR_KEYS="X_Keiro"
CONTINUATION_TARGET_REMARKS_KEYS="NOTICE"

## Delete/chg formatting
DELETE_MODE="mirror_changed"  # reason | mirror_changed

## Organization Parameters
ORIGIN=""
MNT_BY=""
NOTIFY=""
ADMIN_C=""
TECH_C=""
UPD_TO=""
REMARKS=""
X_Keiro=""
NOTICE=""
