##
## Registry profile: RIPE-NONAUTH
##

## common settings
whois_address=""
irr_mail_address=""
SOURCE="RIPE-NONAUTH"
UPDATE_METHOD="email"
AUTH_METHOD="pw_in_body"

## Continuation Options
## Keys listed here must be defined in "Organization Parameters"
CONTINUATION_TARGET_DESCR_KEYS=""
CONTINUATION_TARGET_REMARKS_KEYS="NOTICE"

## Delete/chg formatting
DELETE_MODE="reason"  # reason | mirror_changed
DELETE_REASON_TEMPLATE="{from} {reason}"  # placeholders: {from} {date} {prefix} {descr} {reason}
DELETE_REASON_TEXT="unused route"

## Organization Parameters
ORIGIN=""
MNT_BY=""
NOTIFY=""
ADMIN_C=""
TECH_C=""
UPD_TO=""
REMARKS=""
NOTICE=""
